// examples/vue-example/src/views/BlogPost.vue
<template>
  <div class="blog-post" v-if="post">
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
  </div>
  <div v-else>Loading...</div>
</template>

<script>
import { useHead } from 'head-space'
import { inject, ref, onMounted, watch } from 'vue'
import { useRoute } from 'vue-router'

export default {
  name: 'BlogPost',
  setup() {
    const headSpace = inject('headSpace')
    const route = useRoute()
    const post = ref(null)

    const fetchPost = async (id) => {
      // Simulated API call
      await new Promise(resolve => setTimeout(resolve, 1000))
      post.value = {
        id,
        title: `Blog Post ${id}`,
        content: `This is the content of blog post ${id}.`,
      }
    }

    onMounted(() => fetchPost(route.params.id))

    watch(() => route.params.id, (newId) => fetchPost(newId))

    useHead(() => ({
      title: post.value ? `${post.value.title} | HeadSpace Vue Example` : 'Loading...',
      meta: {
        description: post.value ? `Read ${post.value.title} on our blog` : 'Loading blog post...',
        'og:title': post.value ? `HeadSpace Vue Example - ${post.value.title}` : 'Loading...',
        'og:description': post.value ? `Discover ${post.value.title} in our HeadSpace Vue example` : 'Loading blog post...',
      },
      links: {
        canonical: { href: `https://example.com/blog/${route.params.id}` },
      },
    }), headSpace)

    return { post }
  }
}
</script>

// examples/react-example/src/components/BlogPost.js
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useHead } from 'head-space';

function BlogPost() {
  const { id } = useParams();
  const [post, setPost] = useState(null);

  useEffect(() => {
    // Simulated API call
    setTimeout(() => {
      setPost({
        id,
        title: `Blog Post ${id}`,
        content: `This is the content of blog post ${id}.`,
      });
    }, 1000);
  }, [id]);

  useHead({
    title: post ? `${post.title} | HeadSpace React Example` : 'Loading...',
    meta: {
      description: post ? `Read ${post.title} on our blog` : 'Loading blog post...',
      'og:title': post ? `HeadSpace React Example - ${post.title}` : 'Loading...',
      'og:description': post ? `Discover ${post.title} in our HeadSpace React example` : 'Loading blog post...',
    },
    links: {
      canonical: { href: `https://example.com/blog/${id}` },
    },
  });

  if (!post) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <h1>{post.title}</h1>
      <p>{post.content}</p>
    </div>
  );
}

export default BlogPost;
